// Autogenerated from Pigeon (v0.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package software.solid.fluttervlcplayer;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Messages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class CreateMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String uri;
    public String getUri() { return uri; }
    public void setUri(String setterArg) { this.uri = setterArg; }

    private Long type;
    public Long getType() { return type; }
    public void setType(Long setterArg) { this.type = setterArg; }

    private String packageName;
    public String getPackageName() { return packageName; }
    public void setPackageName(String setterArg) { this.packageName = setterArg; }

    private Boolean autoPlay;
    public Boolean getAutoPlay() { return autoPlay; }
    public void setAutoPlay(Boolean setterArg) { this.autoPlay = setterArg; }

    private Long hwAcc;
    public Long getHwAcc() { return hwAcc; }
    public void setHwAcc(Long setterArg) { this.hwAcc = setterArg; }

    private List<Object> options;
    public List<Object> getOptions() { return options; }
    public void setOptions(List<Object> setterArg) { this.options = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("uri", uri);
      toMapResult.put("type", type);
      toMapResult.put("packageName", packageName);
      toMapResult.put("autoPlay", autoPlay);
      toMapResult.put("hwAcc", hwAcc);
      toMapResult.put("options", options);
      return toMapResult;
    }
    static CreateMessage fromMap(Map<String, Object> map) {
      CreateMessage fromMapResult = new CreateMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object uri = map.get("uri");
      fromMapResult.uri = (String)uri;
      Object type = map.get("type");
      fromMapResult.type = (type == null) ? null : ((type instanceof Integer) ? (Integer)type : (Long)type);
      Object packageName = map.get("packageName");
      fromMapResult.packageName = (String)packageName;
      Object autoPlay = map.get("autoPlay");
      fromMapResult.autoPlay = (Boolean)autoPlay;
      Object hwAcc = map.get("hwAcc");
      fromMapResult.hwAcc = (hwAcc == null) ? null : ((hwAcc instanceof Integer) ? (Integer)hwAcc : (Long)hwAcc);
      Object options = map.get("options");
      fromMapResult.options = (List<Object>)options;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ViewMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      return toMapResult;
    }
    static ViewMessage fromMap(Map<String, Object> map) {
      ViewMessage fromMapResult = new ViewMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SetMediaMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String uri;
    public String getUri() { return uri; }
    public void setUri(String setterArg) { this.uri = setterArg; }

    private Long type;
    public Long getType() { return type; }
    public void setType(Long setterArg) { this.type = setterArg; }

    private String packageName;
    public String getPackageName() { return packageName; }
    public void setPackageName(String setterArg) { this.packageName = setterArg; }

    private Boolean autoPlay;
    public Boolean getAutoPlay() { return autoPlay; }
    public void setAutoPlay(Boolean setterArg) { this.autoPlay = setterArg; }

    private Long hwAcc;
    public Long getHwAcc() { return hwAcc; }
    public void setHwAcc(Long setterArg) { this.hwAcc = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("uri", uri);
      toMapResult.put("type", type);
      toMapResult.put("packageName", packageName);
      toMapResult.put("autoPlay", autoPlay);
      toMapResult.put("hwAcc", hwAcc);
      return toMapResult;
    }
    static SetMediaMessage fromMap(Map<String, Object> map) {
      SetMediaMessage fromMapResult = new SetMediaMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object uri = map.get("uri");
      fromMapResult.uri = (String)uri;
      Object type = map.get("type");
      fromMapResult.type = (type == null) ? null : ((type instanceof Integer) ? (Integer)type : (Long)type);
      Object packageName = map.get("packageName");
      fromMapResult.packageName = (String)packageName;
      Object autoPlay = map.get("autoPlay");
      fromMapResult.autoPlay = (Boolean)autoPlay;
      Object hwAcc = map.get("hwAcc");
      fromMapResult.hwAcc = (hwAcc == null) ? null : ((hwAcc instanceof Integer) ? (Integer)hwAcc : (Long)hwAcc);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class BooleanMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Boolean result;
    public Boolean getResult() { return result; }
    public void setResult(Boolean setterArg) { this.result = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("result", result);
      return toMapResult;
    }
    static BooleanMessage fromMap(Map<String, Object> map) {
      BooleanMessage fromMapResult = new BooleanMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object result = map.get("result");
      fromMapResult.result = (Boolean)result;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class LoopingMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Boolean isLooping;
    public Boolean getIsLooping() { return isLooping; }
    public void setIsLooping(Boolean setterArg) { this.isLooping = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("isLooping", isLooping);
      return toMapResult;
    }
    static LoopingMessage fromMap(Map<String, Object> map) {
      LoopingMessage fromMapResult = new LoopingMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object isLooping = map.get("isLooping");
      fromMapResult.isLooping = (Boolean)isLooping;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PositionMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long position;
    public Long getPosition() { return position; }
    public void setPosition(Long setterArg) { this.position = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("position", position);
      return toMapResult;
    }
    static PositionMessage fromMap(Map<String, Object> map) {
      PositionMessage fromMapResult = new PositionMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object position = map.get("position");
      fromMapResult.position = (position == null) ? null : ((position instanceof Integer) ? (Integer)position : (Long)position);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DurationMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long duration;
    public Long getDuration() { return duration; }
    public void setDuration(Long setterArg) { this.duration = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("duration", duration);
      return toMapResult;
    }
    static DurationMessage fromMap(Map<String, Object> map) {
      DurationMessage fromMapResult = new DurationMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object duration = map.get("duration");
      fromMapResult.duration = (duration == null) ? null : ((duration instanceof Integer) ? (Integer)duration : (Long)duration);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class VolumeMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long volume;
    public Long getVolume() { return volume; }
    public void setVolume(Long setterArg) { this.volume = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("volume", volume);
      return toMapResult;
    }
    static VolumeMessage fromMap(Map<String, Object> map) {
      VolumeMessage fromMapResult = new VolumeMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object volume = map.get("volume");
      fromMapResult.volume = (volume == null) ? null : ((volume instanceof Integer) ? (Integer)volume : (Long)volume);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class PlaybackSpeedMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Double speed;
    public Double getSpeed() { return speed; }
    public void setSpeed(Double setterArg) { this.speed = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("speed", speed);
      return toMapResult;
    }
    static PlaybackSpeedMessage fromMap(Map<String, Object> map) {
      PlaybackSpeedMessage fromMapResult = new PlaybackSpeedMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object speed = map.get("speed");
      fromMapResult.speed = (Double)speed;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SnapshotMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String snapshot;
    public String getSnapshot() { return snapshot; }
    public void setSnapshot(String setterArg) { this.snapshot = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("snapshot", snapshot);
      return toMapResult;
    }
    static SnapshotMessage fromMap(Map<String, Object> map) {
      SnapshotMessage fromMapResult = new SnapshotMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object snapshot = map.get("snapshot");
      fromMapResult.snapshot = (String)snapshot;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackCountMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long count;
    public Long getCount() { return count; }
    public void setCount(Long setterArg) { this.count = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("count", count);
      return toMapResult;
    }
    static TrackCountMessage fromMap(Map<String, Object> map) {
      TrackCountMessage fromMapResult = new TrackCountMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object count = map.get("count");
      fromMapResult.count = (count == null) ? null : ((count instanceof Integer) ? (Integer)count : (Long)count);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SpuTracksMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Map<Integer, String> subtitles;
    public Map<Integer, String> getSubtitles() { return subtitles; }
    public void setSubtitles(Map<Integer, String> setterArg) { this.subtitles = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("subtitles", subtitles);
      return toMapResult;
    }
    static SpuTracksMessage fromMap(Map<String, Object> map) {
      SpuTracksMessage fromMapResult = new SpuTracksMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object subtitles = map.get("subtitles");
      fromMapResult.subtitles = (Map<Integer, String>)subtitles;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SpuTrackMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long spuTrackNumber;
    public Long getSpuTrackNumber() { return spuTrackNumber; }
    public void setSpuTrackNumber(Long setterArg) { this.spuTrackNumber = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("spuTrackNumber", spuTrackNumber);
      return toMapResult;
    }
    static SpuTrackMessage fromMap(Map<String, Object> map) {
      SpuTrackMessage fromMapResult = new SpuTrackMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object spuTrackNumber = map.get("spuTrackNumber");
      fromMapResult.spuTrackNumber = (spuTrackNumber == null) ? null : ((spuTrackNumber instanceof Integer) ? (Integer)spuTrackNumber : (Long)spuTrackNumber);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DelayMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long delay;
    public Long getDelay() { return delay; }
    public void setDelay(Long setterArg) { this.delay = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("delay", delay);
      return toMapResult;
    }
    static DelayMessage fromMap(Map<String, Object> map) {
      DelayMessage fromMapResult = new DelayMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object delay = map.get("delay");
      fromMapResult.delay = (delay == null) ? null : ((delay instanceof Integer) ? (Integer)delay : (Long)delay);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class AddSubtitleMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String uri;
    public String getUri() { return uri; }
    public void setUri(String setterArg) { this.uri = setterArg; }

    private Long type;
    public Long getType() { return type; }
    public void setType(Long setterArg) { this.type = setterArg; }

    private Boolean isSelected;
    public Boolean getIsSelected() { return isSelected; }
    public void setIsSelected(Boolean setterArg) { this.isSelected = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("uri", uri);
      toMapResult.put("type", type);
      toMapResult.put("isSelected", isSelected);
      return toMapResult;
    }
    static AddSubtitleMessage fromMap(Map<String, Object> map) {
      AddSubtitleMessage fromMapResult = new AddSubtitleMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object uri = map.get("uri");
      fromMapResult.uri = (String)uri;
      Object type = map.get("type");
      fromMapResult.type = (type == null) ? null : ((type instanceof Integer) ? (Integer)type : (Long)type);
      Object isSelected = map.get("isSelected");
      fromMapResult.isSelected = (Boolean)isSelected;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class AudioTracksMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Map<Integer, String> audios;
    public Map<Integer, String> getAudios() { return audios; }
    public void setAudios(Map<Integer, String> setterArg) { this.audios = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("audios", audios);
      return toMapResult;
    }
    static AudioTracksMessage fromMap(Map<String, Object> map) {
      AudioTracksMessage fromMapResult = new AudioTracksMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object audios = map.get("audios");
      fromMapResult.audios = (Map<Integer, String>)audios;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class AudioTrackMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long audioTrackNumber;
    public Long getAudioTrackNumber() { return audioTrackNumber; }
    public void setAudioTrackNumber(Long setterArg) { this.audioTrackNumber = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("audioTrackNumber", audioTrackNumber);
      return toMapResult;
    }
    static AudioTrackMessage fromMap(Map<String, Object> map) {
      AudioTrackMessage fromMapResult = new AudioTrackMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object audioTrackNumber = map.get("audioTrackNumber");
      fromMapResult.audioTrackNumber = (audioTrackNumber == null) ? null : ((audioTrackNumber instanceof Integer) ? (Integer)audioTrackNumber : (Long)audioTrackNumber);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class AddAudioMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String uri;
    public String getUri() { return uri; }
    public void setUri(String setterArg) { this.uri = setterArg; }

    private Long type;
    public Long getType() { return type; }
    public void setType(Long setterArg) { this.type = setterArg; }

    private Boolean isSelected;
    public Boolean getIsSelected() { return isSelected; }
    public void setIsSelected(Boolean setterArg) { this.isSelected = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("uri", uri);
      toMapResult.put("type", type);
      toMapResult.put("isSelected", isSelected);
      return toMapResult;
    }
    static AddAudioMessage fromMap(Map<String, Object> map) {
      AddAudioMessage fromMapResult = new AddAudioMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object uri = map.get("uri");
      fromMapResult.uri = (String)uri;
      Object type = map.get("type");
      fromMapResult.type = (type == null) ? null : ((type instanceof Integer) ? (Integer)type : (Long)type);
      Object isSelected = map.get("isSelected");
      fromMapResult.isSelected = (Boolean)isSelected;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class VideoTracksMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Map<Integer, String> videos;
    public Map<Integer, String> getVideos() { return videos; }
    public void setVideos(Map<Integer, String> setterArg) { this.videos = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("videos", videos);
      return toMapResult;
    }
    static VideoTracksMessage fromMap(Map<String, Object> map) {
      VideoTracksMessage fromMapResult = new VideoTracksMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object videos = map.get("videos");
      fromMapResult.videos = (Map<Integer, String>)videos;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class VideoTrackMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Long videoTrackNumber;
    public Long getVideoTrackNumber() { return videoTrackNumber; }
    public void setVideoTrackNumber(Long setterArg) { this.videoTrackNumber = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("videoTrackNumber", videoTrackNumber);
      return toMapResult;
    }
    static VideoTrackMessage fromMap(Map<String, Object> map) {
      VideoTrackMessage fromMapResult = new VideoTrackMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object videoTrackNumber = map.get("videoTrackNumber");
      fromMapResult.videoTrackNumber = (videoTrackNumber == null) ? null : ((videoTrackNumber instanceof Integer) ? (Integer)videoTrackNumber : (Long)videoTrackNumber);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class VideoScaleMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Double scale;
    public Double getScale() { return scale; }
    public void setScale(Double setterArg) { this.scale = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("scale", scale);
      return toMapResult;
    }
    static VideoScaleMessage fromMap(Map<String, Object> map) {
      VideoScaleMessage fromMapResult = new VideoScaleMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object scale = map.get("scale");
      fromMapResult.scale = (Double)scale;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class VideoAspectRatioMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String aspectRatio;
    public String getAspectRatio() { return aspectRatio; }
    public void setAspectRatio(String setterArg) { this.aspectRatio = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("aspectRatio", aspectRatio);
      return toMapResult;
    }
    static VideoAspectRatioMessage fromMap(Map<String, Object> map) {
      VideoAspectRatioMessage fromMapResult = new VideoAspectRatioMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object aspectRatio = map.get("aspectRatio");
      fromMapResult.aspectRatio = (String)aspectRatio;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RendererServicesMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private List<String> services;
    public List<String> getServices() { return services; }
    public void setServices(List<String> setterArg) { this.services = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("services", services);
      return toMapResult;
    }
    static RendererServicesMessage fromMap(Map<String, Object> map) {
      RendererServicesMessage fromMapResult = new RendererServicesMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object services = map.get("services");
      fromMapResult.services = (List<String>)services;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RendererScanningMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String rendererService;
    public String getRendererService() { return rendererService; }
    public void setRendererService(String setterArg) { this.rendererService = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("rendererService", rendererService);
      return toMapResult;
    }
    static RendererScanningMessage fromMap(Map<String, Object> map) {
      RendererScanningMessage fromMapResult = new RendererScanningMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object rendererService = map.get("rendererService");
      fromMapResult.rendererService = (String)rendererService;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RendererDevicesMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private Map<String, String> rendererDevices;
    public Map<String, String> getRendererDevices() { return rendererDevices; }
    public void setRendererDevices(Map<String, String> setterArg) { this.rendererDevices = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("rendererDevices", rendererDevices);
      return toMapResult;
    }
    static RendererDevicesMessage fromMap(Map<String, Object> map) {
      RendererDevicesMessage fromMapResult = new RendererDevicesMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object rendererDevices = map.get("rendererDevices");
      fromMapResult.rendererDevices = (Map<String, String>)rendererDevices;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RenderDeviceMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String rendererDevice;
    public String getRendererDevice() { return rendererDevice; }
    public void setRendererDevice(String setterArg) { this.rendererDevice = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("rendererDevice", rendererDevice);
      return toMapResult;
    }
    static RenderDeviceMessage fromMap(Map<String, Object> map) {
      RenderDeviceMessage fromMapResult = new RenderDeviceMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object rendererDevice = map.get("rendererDevice");
      fromMapResult.rendererDevice = (String)rendererDevice;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class RecordMessage {
    private Long viewId;
    public Long getViewId() { return viewId; }
    public void setViewId(Long setterArg) { this.viewId = setterArg; }

    private String saveDirectory;
    public String getSaveDirectory() { return saveDirectory; }
    public void setSaveDirectory(String setterArg) { this.saveDirectory = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("viewId", viewId);
      toMapResult.put("saveDirectory", saveDirectory);
      return toMapResult;
    }
    static RecordMessage fromMap(Map<String, Object> map) {
      RecordMessage fromMapResult = new RecordMessage();
      Object viewId = map.get("viewId");
      fromMapResult.viewId = (viewId == null) ? null : ((viewId instanceof Integer) ? (Integer)viewId : (Long)viewId);
      Object saveDirectory = map.get("saveDirectory");
      fromMapResult.saveDirectory = (String)saveDirectory;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface VlcPlayerApi {
    void initialize();
    void create(CreateMessage arg);
    void dispose(ViewMessage arg);
    void setStreamUrl(SetMediaMessage arg);
    void play(ViewMessage arg);
    void pause(ViewMessage arg);
    void stop(ViewMessage arg);
    BooleanMessage isPlaying(ViewMessage arg);
    BooleanMessage isSeekable(ViewMessage arg);
    void setLooping(LoopingMessage arg);
    void seekTo(PositionMessage arg);
    PositionMessage position(ViewMessage arg);
    DurationMessage duration(ViewMessage arg);
    void setVolume(VolumeMessage arg);
    VolumeMessage getVolume(ViewMessage arg);
    void setPlaybackSpeed(PlaybackSpeedMessage arg);
    PlaybackSpeedMessage getPlaybackSpeed(ViewMessage arg);
    SnapshotMessage takeSnapshot(ViewMessage arg);
    TrackCountMessage getSpuTracksCount(ViewMessage arg);
    SpuTracksMessage getSpuTracks(ViewMessage arg);
    void setSpuTrack(SpuTrackMessage arg);
    SpuTrackMessage getSpuTrack(ViewMessage arg);
    void setSpuDelay(DelayMessage arg);
    DelayMessage getSpuDelay(ViewMessage arg);
    void addSubtitleTrack(AddSubtitleMessage arg);
    TrackCountMessage getAudioTracksCount(ViewMessage arg);
    AudioTracksMessage getAudioTracks(ViewMessage arg);
    void setAudioTrack(AudioTrackMessage arg);
    AudioTrackMessage getAudioTrack(ViewMessage arg);
    void setAudioDelay(DelayMessage arg);
    DelayMessage getAudioDelay(ViewMessage arg);
    void addAudioTrack(AddAudioMessage arg);
    TrackCountMessage getVideoTracksCount(ViewMessage arg);
    VideoTracksMessage getVideoTracks(ViewMessage arg);
    void setVideoTrack(VideoTrackMessage arg);
    VideoTrackMessage getVideoTrack(ViewMessage arg);
    void setVideoScale(VideoScaleMessage arg);
    VideoScaleMessage getVideoScale(ViewMessage arg);
    void setVideoAspectRatio(VideoAspectRatioMessage arg);
    VideoAspectRatioMessage getVideoAspectRatio(ViewMessage arg);
    RendererServicesMessage getAvailableRendererServices(ViewMessage arg);
    void startRendererScanning(RendererScanningMessage arg);
    void stopRendererScanning(ViewMessage arg);
    RendererDevicesMessage getRendererDevices(ViewMessage arg);
    void castToRenderer(RenderDeviceMessage arg);
    BooleanMessage startRecording(RecordMessage arg);
    BooleanMessage stopRecording(ViewMessage arg);

    /** Sets up an instance of `VlcPlayerApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, VlcPlayerApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.initialize", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              api.initialize();
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.create", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              CreateMessage input = CreateMessage.fromMap((Map<String, Object>)message);
              api.create(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.dispose", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              api.dispose(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setStreamUrl", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              SetMediaMessage input = SetMediaMessage.fromMap((Map<String, Object>)message);
              api.setStreamUrl(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.play", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              api.play(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.pause", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              api.pause(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.stop", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              api.stop(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.isPlaying", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              BooleanMessage output = api.isPlaying(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.isSeekable", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              BooleanMessage output = api.isSeekable(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setLooping", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              LoopingMessage input = LoopingMessage.fromMap((Map<String, Object>)message);
              api.setLooping(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.seekTo", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              PositionMessage input = PositionMessage.fromMap((Map<String, Object>)message);
              api.seekTo(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.position", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              PositionMessage output = api.position(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.duration", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              DurationMessage output = api.duration(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setVolume", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              VolumeMessage input = VolumeMessage.fromMap((Map<String, Object>)message);
              api.setVolume(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVolume", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              VolumeMessage output = api.getVolume(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setPlaybackSpeed", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              PlaybackSpeedMessage input = PlaybackSpeedMessage.fromMap((Map<String, Object>)message);
              api.setPlaybackSpeed(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getPlaybackSpeed", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              PlaybackSpeedMessage output = api.getPlaybackSpeed(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.takeSnapshot", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              SnapshotMessage output = api.takeSnapshot(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getSpuTracksCount", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              TrackCountMessage output = api.getSpuTracksCount(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getSpuTracks", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              SpuTracksMessage output = api.getSpuTracks(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setSpuTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              SpuTrackMessage input = SpuTrackMessage.fromMap((Map<String, Object>)message);
              api.setSpuTrack(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getSpuTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              SpuTrackMessage output = api.getSpuTrack(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setSpuDelay", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              DelayMessage input = DelayMessage.fromMap((Map<String, Object>)message);
              api.setSpuDelay(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getSpuDelay", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              DelayMessage output = api.getSpuDelay(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.addSubtitleTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              AddSubtitleMessage input = AddSubtitleMessage.fromMap((Map<String, Object>)message);
              api.addSubtitleTrack(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getAudioTracksCount", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              TrackCountMessage output = api.getAudioTracksCount(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getAudioTracks", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              AudioTracksMessage output = api.getAudioTracks(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setAudioTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              AudioTrackMessage input = AudioTrackMessage.fromMap((Map<String, Object>)message);
              api.setAudioTrack(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getAudioTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              AudioTrackMessage output = api.getAudioTrack(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setAudioDelay", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              DelayMessage input = DelayMessage.fromMap((Map<String, Object>)message);
              api.setAudioDelay(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getAudioDelay", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              DelayMessage output = api.getAudioDelay(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.addAudioTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              AddAudioMessage input = AddAudioMessage.fromMap((Map<String, Object>)message);
              api.addAudioTrack(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVideoTracksCount", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              TrackCountMessage output = api.getVideoTracksCount(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVideoTracks", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              VideoTracksMessage output = api.getVideoTracks(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setVideoTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              VideoTrackMessage input = VideoTrackMessage.fromMap((Map<String, Object>)message);
              api.setVideoTrack(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVideoTrack", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              VideoTrackMessage output = api.getVideoTrack(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setVideoScale", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              VideoScaleMessage input = VideoScaleMessage.fromMap((Map<String, Object>)message);
              api.setVideoScale(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVideoScale", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              VideoScaleMessage output = api.getVideoScale(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.setVideoAspectRatio", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              VideoAspectRatioMessage input = VideoAspectRatioMessage.fromMap((Map<String, Object>)message);
              api.setVideoAspectRatio(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getVideoAspectRatio", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              VideoAspectRatioMessage output = api.getVideoAspectRatio(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getAvailableRendererServices", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              RendererServicesMessage output = api.getAvailableRendererServices(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.startRendererScanning", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              RendererScanningMessage input = RendererScanningMessage.fromMap((Map<String, Object>)message);
              api.startRendererScanning(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.stopRendererScanning", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              api.stopRendererScanning(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.getRendererDevices", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              RendererDevicesMessage output = api.getRendererDevices(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.castToRenderer", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              RenderDeviceMessage input = RenderDeviceMessage.fromMap((Map<String, Object>)message);
              api.castToRenderer(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.startRecording", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              RecordMessage input = RecordMessage.fromMap((Map<String, Object>)message);
              BooleanMessage output = api.startRecording(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.VlcPlayerApi.stopRecording", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              ViewMessage input = ViewMessage.fromMap((Map<String, Object>)message);
              BooleanMessage output = api.stopRecording(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
