name: Library ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check flutter sdk version
        run: flutter --version

      - name: Get dependencies
        working-directory: ./flutter_vlc_player
        run: flutter pub get

      - name: Setup Dart Code Metrics
        working-directory: ./flutter_vlc_player
        run: dart pub get dart_code_metrics

      - name: Dart Code Metrics
        working-directory: ./flutter_vlc_player
        run: |
          dirs_to_analyze=""
          if [ -d lib ]; then dirs_to_analyze+=" lib"; fi
          if [ -d test ]; then dirs_to_analyze+=" test"; fi
          if [ -d example/lib ]; then dirs_to_analyze+=" example/lib"; fi
          if [ dirs_to_analyze != "" ]
          then
            dart run dart_code_metrics:metrics \
              analyze \
              $dirs_to_analyze \
              --fatal-warnings \
              --fatal-performance \
              --fatal-style
            dart run dart_code_metrics:metrics \
              check-unused-files \
              $dirs_to_analyze \
              --fatal-unused
          fi
      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run tests
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
